# Generated by Django 4.2 on 2023-04-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VT', 'Vetements'), ('CM', 'Cosmetiques'), ('EC', 'Electroniques')], default='VT', max_length=5),
            preserve_default=False,
        ),
    ]
