# Generated by Django 4.2 on 2023-05-01 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_shopper_phone_number_shopper_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='state',
        ),
        migrations.AddField(
            model_name='shopper',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
        ),
    ]
