# Generated by Django 4.2 on 2023-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_shopper_state_shopper_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
