# Generated by Django 4.2 on 2023-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shopper_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='phone_number',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='zip_code',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
